spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.130:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: info_route
          uri: lb://city-info
          predicates:
            - Path=/city-info/**, /info/static/**
          filters:
            - RewritePath=/city-info/, /info/static/**

        - id: manager_route
          uri: lb://city-manager
          predicates:
            - Path=/city-manager/**, /manager/static/**
          filters:
            - RewritePath=/city-manager/, /manager/static/**

        - id: camera_route
          uri: lb://city-camera
          predicates:
            - Path=/city-camera/**, /camera/static/**
          filters:
            - RewritePath=/city-camera/, /camera/static/**

        - id: user_route
          uri: lb://city-user
          predicates:
            - Path=/city-user/**, /user/static/**
          filters:
            - RewritePath=/city-user/, /user/static/**

        - id: third_party_route
          uri: lb://city-third-party
          predicates:
            - Path=/city-third-party/**, /third-party/static/**
          filters:
            - RewritePath=/city-third-party/, /third-party/static/**

  application:
    name: city-gateway

server:
  port: 88

