spring:
  resources:
    static-locations: classpath:/user/static/
  datasource:
    username: root
    password: lyc1289choose
    url: jdbc:mysql://192.168.125.128:3306/city_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.125.128:8848
  application:
    name: city-user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
  mvc:
    static-path-pattern: /user/static/**
  redis:
    host: 192.168.125.128
    port: 6379
    password: lyc1289choose
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

logging:
  level:
    com.lyc.city: debug

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000

kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: 0123456789abcdefghijklmnopqrstuvwxyz
    space: 2
  font:
    color: blue
    name: 宋体,楷体,微软雅黑
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1


